---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  namespace: default
  labels:
    app: drupal
spec:
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
        - name: drupal
          imagePullPolicy: Always
          image: korbah/drupal-local-dev-drupal
          ports:
            - containerPort: 80
          volumeMounts: 
            - mountPath: /mnt/drupal
              name: vol-drupal-files
              subPath: web
      volumes: 
        - name: vol-drupal-files
          persistentVolumeClaim: 
            claimName: drupal-files