---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-local-dev-drupal
  labels:
    app: drupal
spec:
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
        - name: drupal
          imagePullPolicy: Always
          image: dock1a/drupal-local-dev-drupal
          ports:
            - containerPort: 80
