---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  labels:
    app: drupal
spec:
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
        - name: drupal
          imagePullPolicy: Always
          image: korbah/drupal-local-dev-drupal
          env:
          - name: CREDS
            value: "blue"
          ports:
            - containerPort: 80
          volumeMounts: 
            - mountPath: /var/www/html
              name: vol-drupal-files
      volumes: 
        - name: vol-drupal-files
          persistentVolumeClaim: 
            claimName: drupal-files