---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drupal
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: korbah/drupal-local-dev-drupal:~v0.1
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ssh://git@github.com/korbah/drupal.git
    targetRevision: master
    path: environments/staging/drupal
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
