apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-files
  namespace: staging
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard-rwo
  hostPath:
    path: /var/www/html