apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-files
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo