---
apiVersion: v1
kind: Secret
metadata:
  name: drupal
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: ssh://git@github.com/korbah/drupal.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACDrJjvyS12B4OSpUZaUikvXKvCpwt5LrxOj/gQv68dH/AAAAKDG9grvxvYK
    7wAAAAtzc2gtZWQyNTUxOQAAACDrJjvyS12B4OSpUZaUikvXKvCpwt5LrxOj/gQv68dH/A
    AAAEA8VdhmM7LmuhL1Pug5Oxin/KwG/ucBSUjlrtp7wL3rausmO/JLXYHg5KlRlpSKS9cq
    8KnC3kuvE6P+BC/rx0f8AAAAF2FyZ29jZEB5ZWxsb3dwZW5jaWwuY29tAQIDBAUG
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "false"
