apiVersion: v1
kind: Service
metadata:
  name: drupal2-loadbalancer
  namespace: staging
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: drupal2